config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions, only: %i(new create destroy)
  resources :matches
  resources :residents
  resources :organizations
  resources :volunteers



  get '/new_profile' => "volunteers#new_profile", as: :new_profile
  post '/create_profile' => 'volunteers#create_profile', as: :create_profile
  get '/new_availability' => 'volunteers#new_availability', as: :new_availability
  post '/create_availability' => 'volunteers#create_availability', as: :create_availability


  get '/new_resident_profile' => 'residents#new_profile', as: :new_resident_profile
  post '/create_resident_profile' => 'residents#create_profile', as: :create_resident_profile
  get '/new_resident_availability' => 'residents#new_availability', as: :new_resident_availability
  post '/create_resident_availability' => 'residents#create_availability', as: :create_resident_availability
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/get_matches' => "matches#get_matches", as: :get_matches
  get '/show_match/:id' => "matches#show_match", as: :show_match

  post '/submit_police_check' => 'volunteers#submit_police_check', as: :submit_police_check
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  has_secure_password
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://s3-us-west-2.amazonaws.com/abett-static/default-avatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_attached_file :policecheck, styles: {thumbnail: "60x60#"}
  validates_attachment :policecheck, content_type: { content_type: "application/pdf" }

  has_many :organizations, through: :residents
  has_many :matches
  has_many :residents, through: :matches
  #FIELDS
  has_many :availabilities
  has_many :hobbies
  has_many :cultural_backgrounds
  has_many :languages
  has_many :skills
  has_many :interactions
  has_many :work_experiences
  has_many :schoolings

  accepts_nested_attributes_for :hobbies, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :languages, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :cultural_backgrounds, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :interactions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :schoolings, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :work_experiences, reject_if: :all_blank, allow_destroy: true


end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :new_profile, :create_profile, :submit_police_check, :new_availability, :create_availability, :destroy]

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        session[:user_id] = @volunteer.id
        session[:type] = @volunteer.class.name
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully created.' }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1
  # PATCH/PUT /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_profile
    @hobbies = Hobby.setlist
    @interaction = Interaction.setlist
    @language = Language.setlist
    @school = Schooling.setlist_names
    @level = Schooling.setlist_levels
    @specialization = Schooling.setlist_specializations
    @industry = WorkExperience.setlist
    @cultural_background = CulturalBackground.setlist
    @availability = Availability.setlist
    @age_ranges = ['Under 18', '18-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70+']

    @volunteer.hobbies.build if !@volunteer.hobbies.any?
    @volunteer.languages.build if !@volunteer.languages.any?
    @volunteer.cultural_backgrounds.build if !@volunteer.cultural_backgrounds.any?
    @volunteer.interactions.build if !@volunteer.interactions.any?
    @volunteer.schoolings.build if !@volunteer.schoolings.any?
    @volunteer.skills.build if !@volunteer.skills.any?
    @volunteer.work_experiences.build if !@volunteer.work_experiences.any?
  end

  def edit_profile
  end

  def create_profile
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to volunteers_url }
      format.json { head :no_content }
    end
  end

  def check_availabilities
    Availability.check_availabilities(@volunteer)
  end

  def new_availability
  end

  def create_availability
    availabilities = params['availability']['timeslot']
    availabilities.each do |availability|
      Availability.create(timeslot: availability, volunteer_id: @volunteer.id)
    end
    redirect_to volunteer_path(@volunteer)
  end

  def submit_police_check
    if @volunteer.update(volunteer_params)
      redirect_to volunteer_path(@volunteer)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(session[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_params
      params.require(:volunteer).permit(:first_name, :last_name, :email, :phone_number, :to_learn, :neighborhood, :city, :location, :age,  :avatar, :policecheck, :password, :password_confirmation,

      hobbies_attributes: [ :id, :name, :_destroy ],
      languages_attributes: [ :id, :language, :_destroy ],
      cultural_backgrounds_attributes: [ :id, :background, :_destroy],
      interactions_attributes: [ :id, :interaction, :_destroy ],
      schoolings_attributes: [ :id, :name, :level, :specialization, :_destroy ],
      skills_attributes: [ :id, :name, :_destroy ],
      work_experiences_attributes: [ :id, :industry,  :_destroy ])
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<%= form_for(volunteer) do |f| %>
  <% if volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% volunteer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Create Account", :class => "button" %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<div class="dashboard">
  <div class="form">
    <h1>Edit Login Info</h1>

    <%= render '/form_partials/form', user: @volunteer %>

    <%= link_to 'Show', @volunteer %> |
    <%= link_to 'Back', volunteers_path %>
  </div>
</div>

app/views/volunteers/new.html.erb
<div class="dashboard">
  <h1 class="heading">Sign Up as a Volunteer</h1>

  <div class="form">
    <%= render 'form_partials/form', user: @volunteer %>
  </div>
</div>

app/views/volunteers/new_availability.html.erb
<%= render 'form_partials/new_availability', availability_path: '/create_availability' %>

app/views/volunteers/new_profile.html.erb
<div class="dashboard">
  <div class="form">
    <%= form_for @volunteer, url: create_profile_path, method: :post do |f| %>
      <h1>Hi <%= @volunteer.first_name %> <%= @volunteer.last_name %>! Create your profile!</h1>

      <%= f.label "Phone Number" %>
      <%= f.text_field :phone_number %>

      <%= render 'form_partials/new_profile', f: f %>


      <%= f.label "What would you like to learn?"  %>
      <%= f.text_area :to_learn %>

      <%= f.submit "Create Profile" %>
    <% end %>
  </div>
</div>

app/views/volunteers/show.html.erb
<%= render "form_partials/show_profile", user: @volunteer %>

<br><br>
<div class="disclaimer">
  <h3> Volunteer application and screening process</h3><br>
  <ol>
    <li>After a review of your profile, you will receive an invitation to attend a Volunteer Orientation Session.</li>
    <li>Participate in an interview at a mutually agreed upon time. The interview will determine whether the applicant is suitable for a volunteer position that is presently available. Please note: An interview does not guarantee a volunteer position.</li>
    <li>Apply for a police check including a vulnerable sector check. All volunteers are required to obtain a successful police check prior to volunteering.</li>
    <li>The successful volunteer will receive training for their new position as well as a detailed Volunteer description of their new role.
  </ol>
</div>

<% if @volunteer.policecheck.exists? %>
  <p>We have your police check!<p>
<% else %>
  <div>
    <p>Show us that you're cleeeeean.</p>
    <%= form_for @volunteer, url: submit_police_check_path, method: :post do |f| %>
      <%= f.file_field :policecheck %>
      <%= f.submit "Submit Police Check" %>
    <% end %>
  </div>
<% end %>