config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions, only: %i(new create destroy)
  resources :matches
  resources :residents
  resources :organizations
  resources :volunteers



  get '/new_profile' => "volunteers#new_profile", as: :new_profile
  post '/create_profile' => 'volunteers#create_profile', as: :create_profile
  get '/new_availability' => 'volunteers#new_availability', as: :new_availability
  post '/create_availability' => 'volunteers#create_availability', as: :create_availability


  get '/new_resident_profile' => 'residents#new_profile', as: :new_resident_profile
  post '/create_resident_profile' => 'residents#create_profile', as: :create_resident_profile
  get '/new_resident_availability' => 'residents#new_availability', as: :new_resident_availability
  post '/create_resident_availability' => 'residents#create_availability', as: :create_resident_availability
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/get_matches' => "matches#get_matches", as: :get_matches
  get '/show_match/:id' => "matches#show_match", as: :show_match

  post '/submit_police_check' => 'volunteers#submit_police_check', as: :submit_police_check
end

app/views/form_partials/_form.html.erb
<div class="container">

<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit :class => "button" %>
  </div>
<% end %>

</div>

app/views/form_partials/_language_fields.html.erb
<div class="field">
  <%= f.label :language %>
  <%= f.select :language, (@language),  include_blank: true %>
</div>

app/views/form_partials/_new_availability.html.erb
<div class="avail-container">
  <h1>Please choose availabilities!</h1>
  <h2>Select all that apply</h2>
  <div class="checkbox-container">
  <%= form_tag availability_path, method: :post %>
  <table>
    <tr>
      <% Availability.setlist.each do |timeslot| %>
        <%= label_tag "#{timeslot}" %>
        <%= check_box_tag 'availability[timeslot][]', "#{timeslot}" %> <br>
      <% end %>
    </tr>
  </table>
  </div>
</div>
<%= submit_tag "Submit Availability" %>

app/views/form_partials/_new_profile.html.erb
<div class="field">
  <%= f.label "Upload your image" %>
  <%= f.file_field :avatar %>
</div>

<div class="field">
  <%= f.label 'Enter your age' %>
  <%= f.select :age, (@age_ranges), include_blank: true %>
</div>

<div class="field">
  <%= f.label 'Address' %>
  <%= f.text_area :location %>
</div>


<%= f.fields_for :hobbies do |r| %>
  <div class="field">
    <%= r.label :hobbies %>
    <%= r.select :name, (@hobbies), include_blank: true %>
  </div>
<% end %>

<%= f.fields_for :languages do |r| %>
  <%= render 'form_partials/language_fields', f: r %>
<% end %>
<%= link_to_add_association 'add language', f, :languages, partial: 'form_partials/language_fields' %>

<%= f.fields_for :cultural_backgrounds do |r| %>
<div class="field">
  <%= r.label :background %>
  <%= r.select :background, (@cultural_background),  include_blank: true %>
</div>
<% end %>


<%= f.fields_for :interactions do |r| %>
  <div class="field">
    <%= r.label :interaction %>
    <%= r.select :interaction, (@interaction),  include_blank: true %>
  </div>
<% end %>

<h2>School and Work Info</h2>
<%= f.fields_for :schoolings do |r| %>
  <div class="field">
    <%= r.label "Name of School" %>
    <%= r.select :name, (@school),  include_blank: true  %>
  </div>
  <div class="field">
    <%= r.label :level %>
    <%= r.select :level, (@level), include_blank: true  %>
  </div>
  <div class="field">
    <%= r.label :specialization %>
    <%= r.select :specialization, (@specialization),  include_blank: true  %>
  </div>
<% end %>

<%= f.fields_for :work_experiences do |r| %>
  <div class="field">
    <%= r.label :industry %>
    <%= r.select :industry, (@industry),  include_blank: true %>
  </div>
<% end %>

app/views/form_partials/_show_profile.html.erb
<div class="dashboard">
<p id="notice"><%= notice %></p>

<h1><%= user.first_name %>
<%= user.last_name %></h1>

<%= image_tag user.avatar.url(:medium) %>

<p> Welcome to ConnectDem! Set up your profile, then set your availabilities, and find your perfect match!</p>

<% if user.age != nil && user.age != ""%>
  <div class="field">
    <h4> Your age:</h4>
    <%= user.age %>
  </div>
<% end %>

<% if user.hobbies.any? %>
  <div class="field">
    <h4>Your hobbies:</h4>
    <% user.hobbies.each do |hobby| %>
      <p><%= hobby.name %></p>
    <% end %>
  </div>
<% end %>

<% if user.schoolings.any? %>
  <div class="field">
    <h4>Your schooling information:</h4>
    <% user.schoolings.each do |schooling| %>
      <p><%= schooling.name %></p>
      <p><%= schooling.level %></p>
      <p><%= schooling.specialization %></p>
    <% end %>
  </div>
<% end %>

<% if user.languages.any? %>
  <div class="field">
    <h4>Your languages:</h4>
    <% user.languages.each do |language| %>
      <p><%= language.language %></p>
    <% end %>
  </div>
<% end %>

<% if user.cultural_backgrounds.any? %>
  <div class="field">
    <h4>Your cultural background:</h4>
    <% user.cultural_backgrounds.each do |cultural_background| %>
      <p><%= cultural_background.background %></p>
    <% end %>
  </div>
<% end %>

<% if user.work_experiences.any? %>
  <div class="field">
    <h4>Your industry:</h4>
    <% user.work_experiences.each do |industry| %>
      <p><%= industry.industry %></p>
    <% end %>
  </div>
<% end %>

<% if user.location != "" && user.location != nil %>
  <div class="field">
    <h4> Your location:</h4>
    <%= user.location %>
  </div>
<% end %>

<% if user.availabilities.any? %>
  <div class="field">
    <h4>Your availabilities:</h4>
    <% user.availabilities.each do |availability| %>
      <p><%= availability.timeslot %></p>
    <% end %>
  </div>
  <% end %>

<% if user.class == Resident %>
  <% if user.to_teach != nil && user.to_teach != "" %>
    <div class="field">
      <h4>You want to teach this:</h4>
      <%= user.to_teach %>
    </div>
  <% end %>

  <% if user.availabilities.any? %>
    <%= link_to get_matches_path do %>
      <div class="button" id="match-button" style="color: black">Match</div> <!--This button needs to be restyled-->
    <% end %>
  <% end %>
<% else %>
  <% if user.to_learn != nil && user.to_learn != "" %>
    <div class="field">
      <h4>You want to learn this:</h4>
      <%= user.to_learn %>
    </div>
  <% end %>
<% end %>

</div>
<br>