config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions, only: %i(new create destroy)
  resources :matches
  resources :residents
  resources :organizations
  resources :volunteers



  get '/new_profile' => "volunteers#new_profile", as: :new_profile
  post '/create_profile' => 'volunteers#create_profile', as: :create_profile
  get '/new_availability' => 'volunteers#new_availability', as: :new_availability
  post '/create_availability' => 'volunteers#create_availability', as: :create_availability


  get '/new_resident_profile' => 'residents#new_profile', as: :new_resident_profile
  post '/create_resident_profile' => 'residents#create_profile', as: :create_resident_profile
  get '/new_resident_availability' => 'residents#new_availability', as: :new_resident_availability
  post '/create_resident_availability' => 'residents#create_availability', as: :create_resident_availability
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/get_matches' => "matches#get_matches", as: :get_matches
  get '/show_match/:id' => "matches#show_match", as: :show_match

  post '/submit_police_check' => 'volunteers#submit_police_check', as: :submit_police_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dementiahack</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Meera+Inimai|Nunito:300|Palanquin+Dark|Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
    <div class="nav-bar">
      <div class="logo">
        <!-- <%= image_tag(("brain.png"), id: "brain") %> -->
        <h1 class="title">
            <% if session[:user_id] %>
              <% if session[:type] == "Volunteer" %>
                <%= link_to "ConnectDem", volunteer_path(session[:user_id]) %>
              <% end %>
              <% if session[:type] == "Resident" %>
                <%= link_to "ConnectDem", resident_path(session[:user_id]) %>
              <% end %>
            <% else %>
              <%= link_to "ConnectDem", root_url %>
            <% end %>
        </h1>
        <%= link_to "Log in", new_session_path %><p>Have an account already?</p>
      </div>
      <% if session[:user_id]  %>
        <div class="link-bar">
          <% if session[:type] == "Volunteer" %>
          <%= link_to 'Edit Login Info', edit_volunteer_path(session[:user_id]) %>
          <%= link_to 'Set Up Profile', new_profile_path %>
          <%= link_to 'Set Availability', new_availability_path %>
          <% end %>
          <% if session[:type] == "Resident" %>
          <%= link_to 'Edit Login Info', edit_resident_path(session[:user_id]) %>
          <%= link_to 'Set Up Profile', new_resident_profile_path %>
          <%= link_to 'Set Availability', new_resident_availability_path %>
          <% end %>
          <%= link_to 'Log Out', session_path('chocolate mint'), method: :delete %>
        </div>
      <% end %>
    </div>

    <div class="shell">
      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <p class="footer">© 2017 ConnectDem , David R. Stephen H. Richard S. Akshit S. Justin C.</p>
    </footer>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dementiahack</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Meera+Inimai|Nunito:300|Palanquin+Dark|Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body class="homepage">
    <div class="nav-bar">
      <div class="logo">
        <%= image_tag(("brain.png"), id: "brain") %>
        <h1 class="title">
            <% if session[:user_id] %>
              <% if session[:type] == "Volunteer" %>
                <%= link_to "ConnectDem", volunteer_path(session[:user_id]) %>
              <% end %>
              <% if session[:type] == "Resident" %>
                <%= link_to "ConnectDem", resident_path(session[:user_id]) %>
              <% end %>
            <% else %>
              <%= link_to "ConnectDem", root_url %>
            <% end %>
        </h1>

        <% if session[:user_id]  %>
        <div class="link-bar">
          <% if session[:type] == "Volunteer" %>
          <%= link_to 'Edit Login Info', edit_volunteer_path(session[:user_id]) %>
          <%= link_to 'Set Up Profile', new_profile_path %>
          <%= link_to 'Set Availability', new_availability_path %>
          <% end %>
          <% if session[:type] == "Resident" %>
          <%= link_to 'Edit Login Info', edit_resident_path(session[:user_id]) %>
          <%= link_to 'Set Up Profile', new_resident_profile_path %>
          <%= link_to 'Set Availability', new_resident_availability_path %>
          <% end %>
          <%= link_to 'Log Out', session_path('chocolate mint'), method: :delete %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="shell">
      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <p class="footer">© 2017 ConnectDem , David R. Stephen H. Richard S. Akshit S. Justin C.</p>

    </footer>
  </body>
</html>